In [8]:
import torch

# Create a 2x3 tensor filled with zeros
tensor_zeros = torch.zeros(2, 3)
print(tensor_zeros)

# Create a tensor from a list
data = [1, 2, 3, 4, 5, 6]
tensor_from_list = torch.tensor(data)
tensor_from_list = tensor_from_list.reshape(2, 3)  # Reshape the tensor to match the shape of tensor_zeros
print(tensor_from_list)

# Perform element-wise multiplication
result = tensor_zeros * tensor_from_list
print(result)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# Create a 5x5 tensor filled with zeros
dimension = [1, 2, 3, 4, 5, 6, 7, 8 ,9]
tensor_dimension = torch.tensor(dimension) # make matrix
tensor_dimension = tensor_dimension.reshape(3, 3)  # Reshape the tensor to (3, 3)
print(tensor_dimension)

# Create a tensor from a list
data = [1, 2, 3, 4, 5, 6, 7 , 8 ,9]
tensor_from_list = torch.tensor(data) # make matrix
tensor_from_list = tensor_from_list.reshape(3, 3)  # Reshape the tensor to match the shape of tensor_dimension
print(tensor_from_list)

# Perform element-wise multiplication
result = tensor_dimension * tensor_from_list
print(result)

print('result = x*y while x=y and x>10 and y>10 in a (3,3) matrix')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
result = x*y while x=y and x>10 and y>10 in a (3,3) matrix
